### ISSUE TITLE
Add boar exchange

### ISSUE THREAD

**Issue by Gcat101** [BoarBotDevs/BoarBot#38]
Add a command that will allow users to create trade offers for other specific users instead of doing it through the public market.

**Comment by WeslayCodes** [comment]
Direct trading won't be added due to limited capabilities with buttons, select menus, and modals. If Discord ever expands modals to include more than just text input, then this might become a reality. Direct trading was a thing on the pre-alpha version of BoarBot, but it was very cluttered and hard to understand.

Trading may still see some kind of addition in the future, just in a non-traditional way. An idea I'm considering is something similar to the GTS from Pokémon games. I honestly like this idea more than the market since it's more intuitive, but it'll probably be a bit before an update for it will be worked on.

If you have any other suggestions, feel free to post them in our [support server](https://discord.gg/DXSwKHYrCa).

**Comment by Gcat101** [comment]
What if like:
First menu: "What boars would you like to give away?" and 3-5 dropdowns to select the boars.
Second menu: "How much money would you like to give away?" and a number input, 0 by default.
Then the 3rd and 4th menus are the same but from the other side, like "What boars would you like to receive" and "How much money would you like to receive".
Then the 5th menu is a conformation and maybe a warning if the trade is a gift (kinda like steam does it).

Then once the original person confirms it, the other person gets a dm or smth where they can either confirm or deny the offer (maybe even edit it and send it back but that’s probably too advanced). If the offer is declined, the original user will get a followup message in the chat they first ran the trading command saying that it failed, same for if the offer went through.

**Comment by Gcat101** [comment]
I might code it up as a PoC and send a PR, soon™️.

**Comment by WeslayCodes** [comment]
> What if like: First menu: "What boars would you like to give away?" and 3-5 dropdowns to select the boars. 
> Second menu: "How much money would you like to give away?" and a number input, 0 by default.

In the pre-alpha version I had a single select menu you could press up and down buttons to view all boars (since there's a cap of 25 options). Maybe a modal that takes in a boar name and an amount then replies with a button asking the user to confirm? Wouldn't be too difficult as there's already a function in [BoarUtils.ts](https://github.com/WeslayCodes/BoarBot/blob/v1.1.0/src/main/typescript/util/boar/BoarUtils.ts) that's used to search for a boar and returns its page number.

> Then the 5th menu is a conformation and maybe a warning if the trade is a gift (kinda like steam does it).

This could work, could just be a simple recap menu.

> Then once the original person confirms it, the other person gets a dm or smth where they can either confirm or deny the offer (maybe even edit it and send it back but that’s probably too advanced). 

I don't like DMing users unless they opt-in. Can just have a /boar trading command that brings you to a general trading area where you can either navigate to ingoing and outgoing trades or navigate to actually making a trade. This gives users time to accept or decline an offer.

I'll reopen this but only because I'm starting to realize that trading has far less storage requirements than the current market system (and is probably faster too). I'd wait until v1.1.1 releases (which should be shortly after v1.1.0 releases as it patches out code that's no longer needed) to do anything, though, as that version will be far easier to make changes to as an outside contributor.

**Comment by Gcat101** [comment]
> since there's a cap of 25 options

Ahh discord and it’s limitations. The workaround sounds alright though.

> I don't like DMing users unless they opt-in. Can just have a /boar trading command that brings you to a general trading area where you can either navigate to ingoing and outgoing trades or navigate to actually making a trade. This gives users time to accept or decline an offer.

I don’t really think that’s a good idea since you wouldn’t be able to tell when you actually get an offer unless you continuously run the command. I agree DMing people isn’t the best option but imo this is worse.

> I'd wait until v1.1.1 releases (which should be shortly after v1.1.0 releases as it patches out code that's no longer needed) to do anything, though, as that version will be far easier to make changes to as an outside contributor.

I’ll wait till that then 👌

**Comment by Gcat101** [comment]
Hi. I've thought about the situation a bit more and want to express my opinion. To not be an asshole and spam your issues, I'll do it here and then close this since this suggestion is pretty much confirmed already. Consider this a final "fuck you" if you want.

So as I've already said, I been thinking about this drama, and the more I thought about it the less it made sense. Your decision was spontaneous, hostile, and made as if it was the result of a bi-polar disorder. When I thought I had resolved all of the complains you've had, you still backstabbed me and blamed me for it.

And then it clicked. You don't care about your fanbase, you only use them to boost your ego. You are addicted to the number of files in your database directory, the number of servers that boarbot is in, the number of total accumulated boarbucks, the number of people in boar general and so on. You treat your followers as if they are just a statistic in an incremental game, going up and then down a bit, up and again a bit down, but overall growing at a steady pace. You are not addicted to the money, you are not even addicted to the recognition you get, no, you get off of seeing that little number in your head go up, growing your little ego like if that number was the number of centimeters it is in diameter.

And you try to defend yourself by saying "oh it's a game" and "games are supposed to be closed source". Well 1. Your project is not a game, it is a gatcha discord bot and most discord bots ARE open source and 2. There are still games that are open source, sure there are not that many, but it doesn't mean that they're failing.

You also say that the previous commits you've made are now also covered by the same license, which isn't true and I'm pretty sure that's illegal to do. Also I'm pretty sure you didn't ask other contributors before changing the license, which is also illegal. 

You say you welcome contributors, but then do this, just because even the slightest possibility of you losing players makes your ego blow up like the inflated balloon it is.

And that isn't even the case. You've seen how many players we've had as supposed to the main version, you know how many diehard main version fans there are, you know that many of those people will simply not switch away to any other version. And yet, that possibility still scares the shit out of you, sitting somewhere in the back of your mind, reminding you that your ego isn't perfect and people can still have a choice. So instead, you decide that a monopoly would be the best move, established by any means necessary. 

I never said I wouldn't push individual changes upstream from bbce, I never said that I won't help the boarbot I grew to love, I never said that I actively wanted to hurt it. I just didn't have the time to try out those mechanics yet, and before I could you decided to shut me down and reimplement everything yourself.

And after all of this, when we tried to have a calm, serious discussion with you on discord, you "reward" us by deleting the whole argument and banning everybody who disagrees with your. Great attitude.

Good luck getting help, no serious FOSS developer will ever touch this repo with a ten foot poll again.

Sorry for the rant, I'm a bit pissed off.
