### ISSUE TITLE
Add /boar advent

### ISSUE THREAD

**Issue by WeslayCodes** [BoarBotDevs/BoarBot#58]
Add a new temporary view to the Mega Menu that gives players access to an advent calendar. Below are the details:

- Starts on December 1st
- Each day gives a reward
- Every 5 days gives a new Festive Boar
- A reward cannot be claimed after the day has passed
- If a player claims all 25 rewards, they get a new Event Boar

**Comment by SuperDuggy117** [comment]
Probably good to add new profile stats too: **Advents Claimed** and **Calenders Completed**.

**Comment by WeslayCodes** [comment]
Eh, I don't know about stats for something that comes once a year. Also calendars completed would just be how many event boars you have.

**Comment by SuperDuggy117** [comment]
Alright, that's fair enough. 

A different thing I do want to specifically highlight since I kinda forgot to mention it initially was that the calendar shouldn't leak the new boars; their squares should probably show the blank boar image until either you claim it or miss it, would be more fun that way

I did add a note to my proposal document afterwards but wasn't sure if it had gotten missed, thought I'd mention it again.
