### ISSUE TITLE
boar streak not updating correctly

### ISSUE THREAD

**Issue by BeAmazedd** [BoarBotDevs/BoarBot#76]
i have missed 7 individual days of boar daily and my streak has not been reset. im so confused man

![unknown](https://github.com/user-attachments/assets/8c110bfe-ddc1-4807-91f1-bc82f1c0dccc)

**Comment by Double2Proj** [comment]
The way streak works in JE has been changed. Instead of instantly removing all of your streak, it only removes part of it. Specifically, it's supposed to remove 7^X days of streak, where X is the amount of consecutive days you've missed. (However, there is currently a bug with this where it actually removes 7^(X-1) days.) 
It looks like your streak had been reduced by 13, so 6 days of 1 streak being removed, and 1 day of 7 streak being removed.

Can you just confirm that those day numbers seem correct?

**Comment by SuperDuggy117** [comment]
(It's also likely going to be changed to be 7*X rather than 7^X once it's fixed)
